### ISSUE TITLE
Data access

### ISSUE THREAD

**Issue by alisher-ai** [xunge/pytorch_lmdb_imagenet#1]
Hi, thanks for the scripts. I am wondering how could you download the images? I can find neither images nor corresponding urls. Any help would be appreciated

**Comment by xunge** [comment]
test_set: http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_test.tar(12.7GB)
val_set: http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar(6.3GB)
train_set: http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_train.tar(138GB)
