### ISSUE TITLE
A simple script tool

### ISSUE THREAD

**Issue by zjykzj** [xunge/pytorch_lmdb_imagenet#3]
Hi @xunge , Thank you for your realization. 

**first thing**, there was a warning when using folder2lmdb.py

```
folder2lmdb.py:123: DeprecationWarning: 'pyarrow.serialize' is deprecated as of 2.0.0 and will be removed in a future version. Use pickle or the pyarrow IPC functionality instead.
```

i use pickle to replace pyarrow and have a PR

**second thing**, i merge the folder2lmdb to a simple script tool - [ zjykzj/pnno](https://github.com/zjykzj/pnno), you can refer to [pnno/demo/imagenet_lmdb/](https://github.com/zjykzj/pnno/tree/master/demo/imagenet_lmdb) for more use

**Comment by xunge** [comment]
Thanks a lot!
